backend/config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :notifications, only: [:show]
    resources :groups, only: [:show, :create, :update, :destroy]
    resources :member_transactions, only: [:index, :show]
    resources :transactions, only: [:show, :destroy, :create, :update]
    resources :users, only: [:show, :create, :update, :destroy]
    resources :user_groups, only: [:index, :show, :create]
  end

  get 'api/users_email/:email', to: 'api/users#show_by_email', as: 'user_by_email'
  delete '/api/users/:id', to: 'users#destroy'
  get 'api/users_by_group/:id', to: 'api/groups#show_by_group', as: 'users_by_group'
  get 'api/transaction_by_id/:id', to: 'api/transactions#show_by_id', as: 'transaction_by_id'
  get 'api/transactions_by_group/:id', to: 'api/transactions#show_by_group', as: 'transactions_by_group'
end

backend/app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :user 
  belongs_to :group 
end

backend/app/controllers/api/notifications_controller.rb
class Api::NotificationsController < ApplicationController

  # GET /notifications/1
  def show
    notifications = Notification.all().where(user_id: params[:id]).order(:created_at)

    render json: notifications, include: [:group]

  end

  # POST /notifications
  def create
    # @notification = Notification.new(notification_params)

    # if @notification.save
    #   redirect_to @notification, notice: "Notification was successfully created."
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end

  # PATCH/PUT /notifications/1
  def update
    # if @notification.update(notification_params)
    #   redirect_to @notification, notice: "Notification was successfully updated.", status: :see_other
    # else
    #   render :edit, status: :unprocessable_entity
    # end
  end

  # DELETE /notifications/1
  def destroy
    # @notification.destroy
    # redirect_to notifications_url, notice: "Notification was successfully destroyed.", status: :see_other
  end

  private
    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:type, :is_read, :is_archived)
    end
end

backend/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  # GET /notifications/1
  def show
  end

  # POST /notifications
  def create
    # @notification = Notification.new(notification_params)

    # if @notification.save
    #   redirect_to @notification, notice: "Notification was successfully created."
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end

  # PATCH/PUT /notifications/1
  def update
    # if @notification.update(notification_params)
    #   redirect_to @notification, notice: "Notification was successfully updated.", status: :see_other
    # else
    #   render :edit, status: :unprocessable_entity
    # end
  end

  # DELETE /notifications/1
  def destroy
    # @notification.destroy
    # redirect_to notifications_url, notice: "Notification was successfully destroyed.", status: :see_other
  end

  private
    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:type, :is_read, :is_archived)
    end
end

backend/app/helpers/notifications_helper.rb
module NotificationsHelper
end

backend/app/views/notifications/_form.html.erb
<%= form_with(model: notification) do |form| %>
  <% if notification.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
        <% notification.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :is_read, style: "display: block" %>
    <%= form.check_box :is_read %>
  </div>

  <div>
    <%= form.label :is_archived, style: "display: block" %>
    <%= form.check_box :is_archived %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/notifications/_notification.html.erb
<div id="<%= dom_id notification %>">
  <p>
    <strong>Type:</strong>
    <%= notification.type %>
  </p>

  <p>
    <strong>Is read:</strong>
    <%= notification.is_read %>
  </p>

  <p>
    <strong>Is archived:</strong>
    <%= notification.is_archived %>
  </p>

</div>

backend/app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Show this notification", @notification %> |
  <%= link_to "Back to notifications", notifications_path %>
</div>

backend/app/views/notifications/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notifications</h1>

<div id="notifications">
  <% @notifications.each do |notification| %>
    <%= render notification %>
    <p>
      <%= link_to "Show this notification", notification %>
    </p>
  <% end %>
</div>

<%= link_to "New notification", new_notification_path %>

backend/app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render "form", notification: @notification %>

<br>

<div>
  <%= link_to "Back to notifications", notifications_path %>
</div>

backend/app/views/notifications/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @notification %>

<div>
  <%= link_to "Edit this notification", edit_notification_path(@notification) %> |
  <%= link_to "Back to notifications", notifications_path %>

  <%= button_to "Destroy this notification", @notification, method: :delete %>
</div>