backend/config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :notifications, only: [:show]
    resources :groups, only: [:show, :create, :update, :destroy]
    resources :member_transactions, only: [:index, :show]
    resources :transactions, only: [:show, :destroy, :create, :update]
    resources :users, only: [:show, :create, :update, :destroy]
    resources :user_groups, only: [:index, :show, :create]
  end

  get 'api/users_email/:email', to: 'api/users#show_by_email', as: 'user_by_email'
  delete '/api/users/:id', to: 'users#destroy'
  get 'api/users_by_group/:id', to: 'api/groups#show_by_group', as: 'users_by_group'
  get 'api/transaction_by_id/:id', to: 'api/transactions#show_by_id', as: 'transaction_by_id'
  get 'api/transactions_by_group/:id', to: 'api/transactions#show_by_group', as: 'transactions_by_group'
end

backend/app/controllers/api/member_transactions_controller.rb
class Api::MemberTransactionsController < ApplicationController

  # GET /member_transactions
  def index
    member_transactions = MemberTransaction.all
    render json: member_transactions.as_json
  end

  # GET /member_transactions/1
  def show
    user = User.find(params[:id])
    member_transactions = MemberTransaction.where("owner_id = ? OR recipient_id = ?", user.id, user.id)
    render json: member_transactions.as_json
  end

  # GET /member_transactions/new
  def new
    @member_transaction = MemberTransaction.new
  end

  # GET /member_transactions/1/edit
  def edit
  end

  # POST /member_transactions
  def create
    @member_transaction = MemberTransaction.new(member_transaction_params)

    if @member_transaction.save
      redirect_to @member_transaction, notice: "Member transaction was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /member_transactions/1
  def update
    if @member_transaction.update(member_transaction_params)
      redirect_to @member_transaction, notice: "Member transaction was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /member_transactions/1
  def destroy
    @member_transaction.destroy
    redirect_to member_transactions_url, notice: "Member transaction was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_transaction
      @member_transaction = MemberTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_transaction_params
      params.require(:member_transaction).permit(:type, :amount)
    end
end

backend/app/controllers/member_transactions_controller.rb
class MemberTransactionsController < ApplicationController
  before_action :set_member_transaction, only: %i[ show edit update destroy ]

  # GET /member_transactions
  def index
    @member_transactions = MemberTransaction.all
  end

  # GET /member_transactions/1
  def show
  end

  # GET /member_transactions/new
  def new
    @member_transaction = MemberTransaction.new
  end

  # GET /member_transactions/1/edit
  def edit
  end

  # POST /member_transactions
  def create
    @member_transaction = MemberTransaction.new(member_transaction_params)

    if @member_transaction.save
      redirect_to @member_transaction, notice: "Member transaction was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /member_transactions/1
  def update
    if @member_transaction.update(member_transaction_params)
      redirect_to @member_transaction, notice: "Member transaction was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /member_transactions/1
  def destroy
    @member_transaction.destroy
    redirect_to member_transactions_url, notice: "Member transaction was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member_transaction
      @member_transaction = MemberTransaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def member_transaction_params
      params.require(:member_transaction).permit(:type, :amount)
    end
end

backend/app/helpers/member_transactions_helper.rb
module MemberTransactionsHelper
end

backend/app/views/member_transactions/_form.html.erb
<%= form_with(model: member_transaction) do |form| %>
  <% if member_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member_transaction.errors.count, "error") %> prohibited this member_transaction from being saved:</h2>

      <ul>
        <% member_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/member_transactions/_member_transaction.html.erb
<div id="<%= dom_id member_transaction %>">
  <p>
    <strong>Type:</strong>
    <%= member_transaction.type %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= member_transaction.amount %>
  </p>

</div>

backend/app/views/member_transactions/edit.html.erb
<h1>Editing member transaction</h1>

<%= render "form", member_transaction: @member_transaction %>

<br>

<div>
  <%= link_to "Show this member transaction", @member_transaction %> |
  <%= link_to "Back to member transactions", member_transactions_path %>
</div>

backend/app/views/member_transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Member transactions</h1>

<div id="member_transactions">
  <% @member_transactions.each do |member_transaction| %>
    <%= render member_transaction %>
    <p>
      <%= link_to "Show this member transaction", member_transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New member transaction", new_member_transaction_path %>

backend/app/views/member_transactions/new.html.erb
<h1>New member transaction</h1>

<%= render "form", member_transaction: @member_transaction %>

<br>

<div>
  <%= link_to "Back to member transactions", member_transactions_path %>
</div>

backend/app/views/member_transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @member_transaction %>

<div>
  <%= link_to "Edit this member transaction", edit_member_transaction_path(@member_transaction) %> |
  <%= link_to "Back to member transactions", member_transactions_path %>

  <%= button_to "Destroy this member transaction", @member_transaction, method: :delete %>
</div>