backend/config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :notifications, only: [:show]
    resources :groups, only: [:show, :create, :update, :destroy]
    resources :member_transactions, only: [:index, :show]
    resources :transactions, only: [:show, :destroy, :create, :update]
    resources :users, only: [:show, :create, :update, :destroy]
    resources :user_groups, only: [:index, :show, :create]
  end

  get 'api/users_email/:email', to: 'api/users#show_by_email', as: 'user_by_email'
  delete '/api/users/:id', to: 'users#destroy'
  get 'api/users_by_group/:id', to: 'api/groups#show_by_group', as: 'users_by_group'
  get 'api/transaction_by_id/:id', to: 'api/transactions#show_by_id', as: 'transaction_by_id'
  get 'api/transactions_by_group/:id', to: 'api/transactions#show_by_group', as: 'transactions_by_group'
end

backend/app/controllers/api/transactions_controller.rb
class Api::TransactionsController < ApplicationController

  # GET /transactions/1
  def show
    usergroups = UserGroup.where(user_id: params[:id])
    transactions = Transaction.where(group_id: usergroups.pluck(:group_id)).includes(:group, :user).order(transaction_date: :desc)
    render json: transactions.as_json(include: { group: { only: :name }, user: { only: :username }})
  end

  def show_by_id
    transaction = Transaction.includes(:group, :user, :member_transactions).find(params[:id])
  
    transaction.member_transactions.each do |member_transaction|
      recipient_user = User.find(member_transaction.recipient_id)
      member_transaction.recipient_username = recipient_user.username
    end
    
    render json: transaction.as_json(include: {
      group: { only: :name },
      user: { only: :username },
      member_transactions: {}
    })
  end
    
  def show_by_group
    transactions=Transaction.where(group_id: params[:id]).order(created_at: :desc)
    render json: transactions, include: [:group, :user]

  end

  # POST /transactions
  def create
    group = Group.find_by(name: params[:group_name])
    recipient = User.find_by(username: params[:recipient_name])
    transaction_params = {
      user_id: params[:transaction][:user_id],
      group_id: group.id,
      transaction_type: params[:transaction][:transaction_type],
      amount: params[:transaction][:amount],
      recipient_id: recipient.present? ? recipient.id : nil,
      transaction_date: Time.now,
      is_deleted: params[:transaction][:is_deleted]
    }

    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      members = UserGroup.where(group_id: @transaction.group_id).where.not(user_id: @transaction.user_id).pluck(:user_id)
  
      case @transaction.transaction_type
      when 'Expense'
        amount_per_member = @transaction.amount / (members.length + 1)
        members.each do |member|
          MemberTransaction.create!(
            member_transaction_type: @transaction.transaction_type,
            amount: amount_per_member,
            owner_id: @transaction.user_id,
            recipient_id: member,
            group_id: @transaction.group_id,
            transaction_id: @transaction.id
          )
        end
      when 'Payment'
        MemberTransaction.create!(
          member_transaction_type: @transaction.transaction_type,
          amount: @transaction.amount,
          owner_id: @transaction.user_id,
          recipient_id: @transaction.recipient_id,
          group_id: @transaction.group_id,
          transaction_id: @transaction.id
        )
      end
    end
  end

  # PATCH/PUT /transactions/1
  def update
    # if @transaction.update(transaction_params)
    #   redirect_to @transaction, notice: "Transaction was successfully updated.", status: :see_other
    # else
    #   render :edit, status: :unprocessable_entity
    # end
  end

  # DELETE /transactions/1
  def destroy
    # @transaction.destroy
    # redirect_to transactions_url, notice: "Transaction was successfully destroyed.", status: :see_other
  end

  private

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:transaction_type, :amount, :transaction_date, :is_deleted, :user_id, :recipient_name, :group_name)
    end
end

backend/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  # GET /transactions/1
  def show
  end

  # POST /transactions
  def create
    # @transaction = Transaction.new(transaction_params)

    # if @transaction.save
    #   redirect_to @transaction, notice: "Transaction was successfully created."
    # else
    #   render :new, status: :unprocessable_entity
    # end
  end

  # PATCH/PUT /transactions/1
  def update
    # if @transaction.update(transaction_params)
    #   redirect_to @transaction, notice: "Transaction was successfully updated.", status: :see_other
    # else
    #   render :edit, status: :unprocessable_entity
    # end
  end

  # DELETE /transactions/1
  def destroy
    # @transaction.destroy
    # redirect_to transactions_url, notice: "Transaction was successfully destroyed.", status: :see_other
  end

  private

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:type, :amount, :transaction_date, :is_deleted)
    end
end

backend/app/helpers/transactions_helper.rb
module TransactionsHelper
end

backend/app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :transaction_date, style: "display: block" %>
    <%= form.date_field :transaction_date %>
  </div>

  <div>
    <%= form.label :is_deleted, style: "display: block" %>
    <%= form.check_box :is_deleted %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Type:</strong>
    <%= transaction.type %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= transaction.amount %>
  </p>

  <p>
    <strong>Transaction date:</strong>
    <%= transaction.transaction_date %>
  </p>

  <p>
    <strong>Is deleted:</strong>
    <%= transaction.is_deleted %>
  </p>

</div>

backend/app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

backend/app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render transaction %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path %>

backend/app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>

backend/app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @transaction %>

<div>
  <%= link_to "Edit this transaction", edit_transaction_path(@transaction) %> |
  <%= link_to "Back to transactions", transactions_path %>

  <%= button_to "Destroy this transaction", @transaction, method: :delete %>
</div>